/*
 * B. Write and test a Y86-64 program consisting of the function and test code.
You may find it useful to pattern your implementation after x86-64 code
generated by compiling your C code. Although pointer comparisons are
normally done using unsigned arithmetic, you can use signed arithmetic for
this exercise.
*/

bubble_a:
    irmovq  $8, %r8
outer_loop:
    rrmovq  %rsi, %rax
    xorq    %rdi, %rax
    je      done
    subq    %r8, %rsi
    rrmovq  %rdi, %rcx
    rrmovq  %rdi, %rdx
inner_loop:
    rrmovq  %rcx, %rax
    xorq    %rsi, %rax
    je      outer_loop
    addq    %r8, %rdx
    mrmovq  (%rcx), %r10
    mrmovq  (%rdx), %r11
    rrmovq  %r10, %rax
    subq    %r11, %rax
    jle     noswap
    rmmovq  %r10, (%rdx)
    rmmovq  %r11, (%rcx)
noswap:
    addq    %r8, %rcx
    jmp     inner_loop
sorted:
    ret
